#!/usr/bin/env bash
# Install HAproxy
sudo apt-get update -y
sudo apt-get install haproxy -y

config="
frontend codesinger.tech
	bind *:80
	default_backend webservers

backend webservers
	balance roundrobin
	server 353898-web-01 54.160.124.63:80 check
	server 353898-web-02 54.158.177.163:80 check"

echo "$config" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart