#!/usr/bin/env bash
#This scirpt prints FizzBuzz when the number is a multiple of 3 and 5 fizz for 3 buzz 5
for ((x=1;x<=100;x++))
do
    if ((x % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((x % 3 == 0))
    then
        echo "Fizz"
    elif ((x % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$x"
    fi
done