#!/usr/bin/env bash
#This script prints Best school 10 times but prints Hi on the 9th iteration
i=1
while [ $i -le 10 ]
do
	echo "Best School"
    sleep 1
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	i=$((i+1))
done