#!/usr/bin/env bash
# This scirpt changes localhost to 127.0.0.2 and change facebook.com to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old
sudo sed -i 's/^127\.0\.0\.1/127.0.0.2/' /etc/hosts
sudo sed -i 's/^.*facebook\.com/8.8.8.8 facebook.com/' /etc/hosts